# Generated by Django 4.2.1 on 2023-05-19 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Display', '0002_playlist_name_video__inherited_video_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='videos',
            field=models.ManyToManyField(related_name='playlists', to='Display.video'),
        ),
    ]
