# Generated by Django 4.2.1 on 2023-05-19 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Display', '0003_playlist_videos'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='video_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
