# Generated by Django 4.2.1 on 2023-05-19 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Display', '0004_video_video_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='video_id',
        ),
    ]
