# Generated by Django 4.2.1 on 2023-05-20 18:40

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Display', '0005_remove_video_video_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='_inherited',
        ),
        migrations.AddField(
            model_name='video',
            name='text',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
