# Generated by Django 4.2.1 on 2023-05-20 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Display', '0006_remove_video__inherited_video_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='_inherited',
            field=models.BooleanField(default=False),
        ),
    ]
