# Generated by Django 4.2.1 on 2023-05-20 19:51

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Display', '0007_video__inherited'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='text',
        ),
        migrations.AddField(
            model_name='video',
            name='words',
            field=ckeditor.fields.RichTextField(default=''),
        ),
    ]
